routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.homepage');
});
Route::get('/about', function () {
    return view('frontend.innerpages.about');
});
Route::get('/blog', function () {
    return view('frontend.innerpages.blog');
});
Route::get('/contact', function () {
    return view('frontend.innerpages.contact');
});
Auth::routes();

Route::middleware('auth')->group(function () {
	Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('songs', 'SongController');
    Route::resource('artists', 'ArtistController');
    Route::resource('lyrics', 'LyricsController');
    Route::resource('chords', 'ChordsController');
});

app/Http/Controllers/LyricsController.php
<?php

namespace App\Http\Controllers;

use App\Model\Lyrics;
use App\Model\Song;
use Illuminate\Http\Request;

class LyricsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $songs = Song::all();
        $lyrics = Lyrics::all();
        return view('backend.lyrics.index', compact('songs', 'lyrics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $songs = Song::all();
        return view('backend.lyrics.create', compact('songs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Lyrics::create($request->all());
        return redirect('/lyrics')->with('success', 'Lyrics is added successfully!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Lyrics  $lyrics
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lyric = Lyrics::findOrFail($id);
        return response()->json(['data' => $lyric]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Lyrics  $lyrics
     * @return \Illuminate\Http\Response
     */
    public function edit(Lyrics $lyrics)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Lyrics  $lyrics
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lyrics $lyrics)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Lyrics  $lyrics
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lyrics $lyrics)
    {
        //
    }
}

resources/views/backend/lyrics/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-6">
		<form action="{{ route('lyrics.store') }}" method="POST">
			@csrf
			<div class="card">
				<div class="card-header">
					<h4 class="card-title">Add Lyrics</h4>
				</div>
				<div class="card-body">
					<div class="form-group">
						<label for="song_id">Select Song</label>
						<select name="song_id" class="form-control">
							<option value="">Select the Song</option>
							@foreach($songs as $song)
								<option value="{{ $song->id }}">{{ $song->title }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label for="lyrics">Lyrics</label>
						<textarea name="lyrics" cols="30" rows="50" class="form-control"></textarea>
					</div>
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/backend/lyrics/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-4">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">List of Lyrics</h4>
				<div>
					<a href="{{ route('lyrics.create') }}" class="btn">
						Add New Lyrics
					</a>
				</div>    
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table">
						<thead class="text-primary">                   
							<tr>
								<th>    
									S.N  
								</th>
								<th> 
									Song
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach($songs as $song)
							<tr>
								<td>    
									{{ $loop->iteration }}
								</td>
								<td> 
									@foreach($lyrics as $lyric)
										@if($lyric->song_id == $song->id)
          									<button class="btn btn-primary" onclick="displayLyrics(<?php echo $lyric->id; ?>)">
          										{{ $song->title }}
          									</button>
          								@else
          									<button class="btn btn-primary" disabled>
          										{{ $song->title }}
          									</button>
										@endif
									@endforeach
								</td>
							</tr>
							@endforeach  
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="card" id="showLyrics">

		</div>
	</div>
</div>
<script>
	function displayLyrics(id){
		fetch('http://127.0.0.1:8000/lyrics/' + id)
		.then((res) => {
			res.json().then((data) => {
				$('#showLyrics').css('opacity', '1');
				$('#showLyrics').append('<pre>'+ data.data.lyrics +'</pre>');
			})
		})
		.catch((error) => {
			console.log(error.json())
		});
	}
</script>
@endsection