routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.homepage');
});
Route::get('/about', function () {
    return view('frontend.innerpages.about');
});
Route::get('/blog', function () {
    return view('frontend.innerpages.blog');
});
Route::get('/contact', function () {
    return view('frontend.innerpages.contact');
});
Auth::routes();

Route::middleware('auth')->group(function () {
	Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('songs', 'SongController');
    Route::resource('artists', 'ArtistController');
    Route::resource('lyrics', 'LyricsController');
    Route::resource('chords', 'ChordsController');
});

resources/views/backend/dashboard.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-lg-4">
		<div class="card card-chart">
			<div class="card-header">
				<h5 class="card-category">Global Sales</h5>
				<h4 class="card-title">Shipped Products</h4>
				<div class="dropdown">
					<button type="button" class="btn btn-round btn-outline-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown">
						<i class="now-ui-icons loader_gear"></i>
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="#">Action</a>
						<a class="dropdown-item" href="#">Another action</a>
						<a class="dropdown-item" href="#">Something else here</a>
						<a class="dropdown-item text-danger" href="#">Remove Data</a>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="chart-area">
					<canvas id="lineChartExample"></canvas>
				</div>
			</div>
			<div class="card-footer">
				<div class="stats">
					<i class="now-ui-icons arrows-1_refresh-69"></i> Just Updated
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4 col-md-6">
		<div class="card card-chart">
			<div class="card-header">
				<h5 class="card-category">2018 Sales</h5>
				<h4 class="card-title">All products</h4>
				<div class="dropdown">
					<button type="button" class="btn btn-round btn-outline-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown">
						<i class="now-ui-icons loader_gear"></i>
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="#">Action</a>
						<a class="dropdown-item" href="#">Another action</a>
						<a class="dropdown-item" href="#">Something else here</a>
						<a class="dropdown-item text-danger" href="#">Remove Data</a>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="chart-area">
					<canvas id="lineChartExampleWithNumbersAndGrid"></canvas>
				</div>
			</div>
			<div class="card-footer">
				<div class="stats">
					<i class="now-ui-icons arrows-1_refresh-69"></i> Just Updated
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4 col-md-6">
		<div class="card card-chart">
			<div class="card-header">
				<h5 class="card-category">Email Statistics</h5>
				<h4 class="card-title">24 Hours Performance</h4>
			</div>
			<div class="card-body">
				<div class="chart-area">
					<canvas id="barChartSimpleGradientsNumbers"></canvas>
				</div>
			</div>
			<div class="card-footer">
				<div class="stats">
					<i class="now-ui-icons ui-2_time-alarm"></i> Last 7 days
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="card  card-tasks">

			<div class="card-header ">
				<h5 class="card-category">Backend development</h5>
				<h4 class="card-title">Tasks</h4>
			</div>

			<div class="card-body ">
				<div class="table-full-width table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td>
									<div class="form-check">
										<label class="form-check-label">
											<input class="form-check-input" type="checkbox" checked>
											<span class="form-check-sign"></span>
										</label>
									</div>
								</td>

								<td class="text-left">Sign contract for "What are conference organizers afraid of?"</td>
								<td class="td-actions text-right">
									<button type="button" rel="tooltip" title="" class="btn btn-info btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Edit Task">
										<i class="now-ui-icons ui-2_settings-90"></i>
									</button>
									<button type="button" rel="tooltip" title="" class="btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Remove">
										<i class="now-ui-icons ui-1_simple-remove"></i>
									</button>
								</td>
							</tr>
							<tr>
								<td>
									<div class="form-check">
										<label class="form-check-label">
											<input class="form-check-input" type="checkbox">
											<span class="form-check-sign"></span>
										</label>
									</div>
								</td>

								<td class="text-left">Lines From Great Russian Literature? Or E-mails From My Boss?</td>
								<td class="td-actions text-right">
									<button type="button" rel="tooltip" title="" class="btn btn-info btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Edit Task">
										<i class="now-ui-icons ui-2_settings-90"></i>
									</button>
									<button type="button" rel="tooltip" title="" class="btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Remove">
										<i class="now-ui-icons ui-1_simple-remove"></i>
									</button>
								</td>
							</tr>
							<tr>
								<td>
									<div class="form-check">
										<label class="form-check-label">
											<input class="form-check-input" type="checkbox" checked>
											<span class="form-check-sign"></span>
										</label>
									</div>
								</td>

								<td class="text-left">Flooded: One year later, assessing what was lost and what was found when a ravaging rain swept through metro Detroit
								</td>
								<td class="td-actions text-right">
									<button type="button" rel="tooltip" title="" class="btn btn-info btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Edit Task">
										<i class="now-ui-icons ui-2_settings-90"></i>
									</button>
									<button type="button" rel="tooltip" title="" class="btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Remove">
										<i class="now-ui-icons ui-1_simple-remove"></i>
									</button>
								</td>
							</tr>
						</tbody>
					</table>
				</div>



			</div>   
			<div class="card-footer ">
				<hr>
				<div class="stats">
					<i class="now-ui-icons loader_refresh spin"></i> Updated 3 minutes ago
				</div>
			</div>

		</div>
	</div>
	<div class="col-md-6">
		<div class="card">
			<div class="card-header">
				<h5 class="card-category">All Persons List</h5>
				<h4 class="card-title"> Employees Stats</h4>

			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table">
						<thead class=" text-primary">
							<th >
								Name
							</th>
							<th >
								Country
							</th>
							<th >
								City
							</th>
							<th  class="text-right" >
								Salary
							</th>
						</thead>
						<tbody>
							<tr >
								<td >
									Dakota Rice
								</td>
								<td >
									Niger
								</td>
								<td >
									Oud-Turnhout
								</td>
								<td  class="text-right" >
									$36,738
								</td>
							</tr>
							<tr >
								<td >
									Minerva Hooper
								</td>
								<td >
									Curaçao
								</td>
								<td >
									Sinaai-Waas
								</td>
								<td  class="text-right" >
									$23,789
								</td>
							</tr>
							<tr >
								<td >
									Sage Rodriguez
								</td>
								<td >
									Netherlands
								</td>
								<td >
									Baileux
								</td>
								<td  class="text-right" >
									$56,142
								</td>
							</tr>
							<tr >
								<td >
									Doris Greene
								</td>
								<td >
									Malawi
								</td>
								<td >
									Feldkirchen in Kärnten
								</td>
								<td  class="text-right" >
									$63,542
								</td>
							</tr>
							<tr >
								<td >
									Mason Porter
								</td>
								<td >
									Chile
								</td>
								<td >
									Gloucester
								</td>
								<td  class="text-right" >
									$78,615
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/footer.blade.php
<footer class="footer" >
  <div class=" container-fluid ">
   <div class="copyright" id="copyright">
    &copy; <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script>, Designed & Developed by <a href="#" target="_blank">Suman Mali</a>.
  </div>
</div>
</footer>

resources/views/backend/navbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
 <div class="container-fluid">
  <div class="navbar-wrapper">

   <div class="navbar-toggle">
    <button type="button" class="navbar-toggler">
     <span class="navbar-toggler-bar bar1"></span>
     <span class="navbar-toggler-bar bar2"></span>
     <span class="navbar-toggler-bar bar3"></span>
   </button>
 </div>

 <a class="navbar-brand" href="#pablo">Dashboard</a>
</div>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-bar navbar-kebab"></span>
 <span class="navbar-toggler-bar navbar-kebab"></span>
 <span class="navbar-toggler-bar navbar-kebab"></span>
</button>

<div class="collapse navbar-collapse justify-content-end" id="navigation">


  <form>
    <div class="input-group no-border">
      <input type="text" value="" class="form-control" placeholder="Search...">
      <div class="input-group-append">
       <div class="input-group-text">
         <i class="now-ui-icons ui-1_zoom-bold"></i>
       </div>
     </div>
   </div>
 </form>

 <ul class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="#pablo">
      <i class="now-ui-icons media-2_sound-wave"></i>
      <p>
        <span class="d-lg-none d-md-block">Stats</span>
      </p>
    </a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="now-ui-icons location_world"></i>
      <p>
        <span class="d-lg-none d-md-block">Some Actions</span>
      </p>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('logout') }}"
    onclick="event.preventDefault();
    document.getElementById('logout-form').submit();">
    <i class="now-ui-icons users_single-02"></i>
    <p>
      <span class="d-lg-none d-md-block">Account</span>
    </p>
  </a>
  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
  </form>
</li>
</ul> 
</div>
</div>
</nav>

resources/views/backend/sidebar.blade.php
<div class="sidebar" data-color="orange">
  <div class="logo">
    <a href="/" class="simple-text logo-normal">
      &nbsp;&nbsp;7 Wonders Band
    </a>
  </div>
  <div class="sidebar-wrapper" id="sidebar-wrapper">
    <ul class="nav"> 
      <li class="active "  >
        <a href="/home">

          <i class="now-ui-icons design_app"></i>

          <p>Dashboard</p>
        </a>
      </li>
      <li >
        <a href="{{ route('artists.index') }}">

          <i class="now-ui-icons users_single-02"></i>

          <p>Artists</p>
        </a>
      </li>
      <li >
        <a href="{{ route('songs.index') }}">

          <i class="now-ui-icons tech_headphones"></i>

          <p>Songs</p>
        </a>
      </li>
      <li >
        <a href="{{ route('lyrics.index') }}">

          <i class="now-ui-icons education_agenda-bookmark"></i>

          <p>Lyrics</p>
        </a>
      </li>
      <li >
        <a href="{{ route('chords.index') }}">

          <i class="now-ui-icons media-2_note-03"></i>

          <p>Chords</p>
        </a>
      </li>
      <li >
        <a href="#">

          <i class="now-ui-icons users_single-02"></i>

          <p>User Profile</p>
        </a>
      </li> 
    </ul>
  </div>
</div>