routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.homepage');
});
Route::get('/about', function () {
    return view('frontend.innerpages.about');
});
Route::get('/blog', function () {
    return view('frontend.innerpages.blog');
});
Route::get('/contact', function () {
    return view('frontend.innerpages.contact');
});
Auth::routes();

Route::middleware('auth')->group(function () {
	Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('songs', 'SongController');
    Route::resource('artists', 'ArtistController');
    Route::resource('lyrics', 'LyricsController');
    Route::resource('chords', 'ChordsController');
});

app/Http/Controllers/SongController.php
<?php

namespace App\Http\Controllers;

use App\Model\Song;
use App\Model\Artist;
use Illuminate\Http\Request;
use App\Http\Requests\Song\createRequestSong;
use App\Repositories\SongRepository;

class SongController extends Controller
{
    protected $songRepo;

    public function __construct(SongRepository $repo){
        $this->songRepo = $repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $songs = Song::all();
        $artists = Artist::orderBy('name')->get();
        return view('backend.songs.index', compact('songs', 'artists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $artists = Artist::orderBy('name')->get();
        return view('backend.songs.create', compact('artists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(createRequestSong $request)
    {
        $song = $this->songRepo->create($request);
        return redirect()->back()->with('success', 'A new song is added successfully!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Song  $song
     * @return \Illuminate\Http\Response
     */
    public function show(Song $song)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Song  $song
     * @return \Illuminate\Http\Response
     */
    public function edit(Song $song)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Song  $song
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Song $song)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Song  $song
     * @return \Illuminate\Http\Response
     */
    public function destroy(Song $song)
    {
        //
    }
}

resources/views/backend/songs/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">Add New Song</h4>     
			</div>
			<div class="card-body">
				<form action="{{ route('songs.store') }}" method="POST" class="addForm" enctype="multipart/form-data">
					@csrf
					<div class="form-group col-md-4">
						<label for="title">Song Title</label>
						<input type="text" name="title" class="form-control" required>
					</div>
					<div class="form-group col-md-4">
						<label for="artist_id">Artist</label>
						<select name="artist_id" class="form-control" required>
							<option value="">Select Artist</option>
							@foreach($artists as $artist)
								<option value="{{ $artist->id }}">{{ $artist->name }}</option>	
							@endforeach
						</select>
					</div>
					<div class="form-group col-md-4">
						<label for="genre">Genre</label>
						<input type="text" name="genre" class="form-control">
					</div>
					<div class="form-group col-md-4">
						<label for="scale">Scale</label>
						<input type="text" name="scale" class="form-control">
					</div>
					<div class="form-group col-md-4">
						<label for="beat">Beat</label>
						<input type="text" name="beat" class="form-control">
					</div>
					<div class="form-group col-md-4">
						<label for="strumming">Strumming</label>
						<input type="text" name="strumming" class="form-control">
					</div>
					<div class="form-group col-md-4">
						<label for="level">Level</label>
						<input type="text" name="level" class="form-control">
					</div>
					<div class="form-group col-md-4">
						<label for="audio">Upload Audio</label>
						<input type="file" name="audio" class="form-control" accept="audio/mp3, audio/wav, audio/aac"/>
					</div>

					<button type="submit" class="btn btn-block col-md-4">Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	function popAddArtist(){
		$('#addArtist').modal();
	}

</script>
@endsection

resources/views/backend/songs/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">
					List of Song
				</h4>
				<div>
					<a href="{{ route('songs.create') }}" class="btn">
						Add New Song
					</a>
				</div>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table">
						<thead class="text-primary">                   
							<tr>
								<th>    
									S.N  
								</th>
								<th>
									Title   
								</th>
								<th>
									Artist
								</th>
								<th>
									Genre  
								</th>
								<th>   
									Beat  
								</th>
								<th>   
									Scale  
								</th>
								<th>   
									Level  
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach($songs as $song)
							<tr>
								<td>    
									{{ $loop->iteration }}
								</td>
								<td> 
									{{ $song->title }}   
								</td>
								<td>
								@foreach($artists as $artist)
									@if($artist->id == $song->artist_id)
										{{ $artist->name }}
									@endif
								@endforeach 
								</td>
								<td>   
									{{ $song->genre }}  
								</td>
								<td>   
									{{ $song->beat }}  
								</td>
								<td>   
									{{ $song->scale }}  
								</td>
								<td>   
									{{ $song->level }}  
								</td>
							</tr>
							@endforeach  
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection